[build]
  publish = "public"  # ✅ 배포할 폴더 (public 디렉토리를 Netlify가 배포 대상으로 인식)

[[headers]]
  for = "/assets/*"  # ✅ assets 폴더에 대한 헤더 설정
  [headers.values]
    Cache-Control = "public, max-age=31536000"  # 캐시를 길게 유지하여 성능 최적화
