[build]
  command = "npm run build"
  publish = "public"  # 정적 파일 제공 폴더

[context.production]
  environment = { NODE_VERSION = "18" }  # Node.js 버전 설정

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200